# -*- coding: utf-8 -*-
"""four-point probe simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h5KfZ6wvReIpp98LAix1QsilZn16EozN
"""

import argparse
import csv
import math
from dataclasses import dataclass, field

import numpy as np
import matplotlib.pyplot as plt

Q_ELEMENTARY = 1.602176634e-19  # Coulombs


@dataclass
class SpeciesParams:
    """Physically-motivated (illustrative) recovery parameters per implant species.

    Attributes
    ----------
    name : str
        Species label (e.g. "N", "Ga", "In", "Kr").
    r_damaged : float
        Sheet resistance immediately post-implant, before annealing [ohm/sq].
    r_floor : float
        Asymptotic sheet resistance after full recovery [ohm/sq].
    tau : float
        Recovery "time constant" in anneal-stage units (larger = slower recovery).
    activation_fraction : float
        Fraction of implanted dose that ultimately activates as free carriers.
    """

    name: str
    r_damaged: float
    r_floor: float
    tau: float
    activation_fraction: float


# Illustrative starting points per species. Kr (noble gas, non-doping control)
# is deliberately given a much higher floor / weaker recovery since it should
# not activate as an electrical dopant.
DEFAULT_SPECIES = {
    "N": SpeciesParams("N", r_damaged=5.0e4, r_floor=800.0, tau=2.2, activation_fraction=0.35),
    "Ga": SpeciesParams("Ga", r_damaged=4.2e4, r_floor=550.0, tau=1.8, activation_fraction=0.45),
    "In": SpeciesParams("In", r_damaged=4.8e4, r_floor=650.0, tau=2.0, activation_fraction=0.40),
    "Kr": SpeciesParams("Kr", r_damaged=6.0e4, r_floor=4.0e4, tau=6.0, activation_fraction=0.02),
}


def sheet_resistance_recovery(stage: np.ndarray, params: SpeciesParams, dose: float, dose_ref: float = 1e14) -> np.ndarray:
    """Model sheet resistance vs. anneal stage as exponential recovery.

    R_s(stage) = R_floor + (R_damaged - R_floor) * exp(-stage / tau)

    Higher implant dose creates more damage -> slightly higher starting
    resistance and slightly slower recovery, scaled relative to a
    reference dose.
    """
    dose_scale = math.log10(max(dose, 1e10) / dose_ref) * 0.15 + 1.0
    r_damaged = params.r_damaged * dose_scale
    tau = params.tau * dose_scale
    return params.r_floor + (r_damaged - params.r_floor) * np.exp(-stage / tau)


def sheet_carrier_density(dose: float, activation_fraction: float, depth_cm: float = 1.5e-6) -> float:
    """Estimate sheet carrier density n_s [cm^-2] from implant dose and activation fraction.

    dose is given in ions/cm^2 (a standard implant fluence unit).
    depth_cm is the implant depth converted to cm (default ~150 nm, per SRIM target).
    """
    return dose * activation_fraction


def carrier_mobility(sheet_resistance: np.ndarray, n_s: float) -> np.ndarray:
    """Compute Hall-derived carrier mobility [cm^2/(V*s)] from R_s and n_s.

    mu = 1 / (q * n_s * R_s), with R_s in ohm/sq and n_s in cm^-2.
    """
    n_s_safe = max(n_s, 1e6)  # avoid division by zero for negligible activation
    return 1.0 / (Q_ELEMENTARY * n_s_safe * sheet_resistance)


def run_simulation(species_list, doses, n_stages=8):
    """Run the recovery simulation across species and doses.

    Returns a list of dict rows suitable for CSV export / plotting.
    """
    stages = np.arange(n_stages)
    rows = []
    for sp_name in species_list:
        params = DEFAULT_SPECIES[sp_name]
        for dose in doses:
            r_s = sheet_resistance_recovery(stages, params, dose)
            n_s = sheet_carrier_density(dose, params.activation_fraction)
            mu = carrier_mobility(r_s, n_s)
            for stage, r, m in zip(stages, r_s, mu):
                rows.append(
                    {
                        "species": sp_name,
                        "dose_cm2": dose,
                        "anneal_stage": int(stage),
                        "sheet_resistance_ohm_sq": float(r),
                        "mobility_cm2_Vs": float(m),
                    }
                )
    return rows


def save_csv(rows, path):
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)
    print(f"Saved {len(rows)} rows to {path}")


def plot_results(rows, save_path=None):
    """Two-panel plot: sheet resistance recovery and mobility, both vs anneal stage."""
    species_list = sorted(set(r["species"] for r in rows))
    doses = sorted(set(r["dose_cm2"] for r in rows))

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    ax_r, ax_mu = axes

    colors = plt.cm.viridis(np.linspace(0, 0.85, len(species_list)))
    linestyles = ["-", "--", "-.", ":"]

    for si, sp in enumerate(species_list):
        for di, dose in enumerate(doses):
            subset = [r for r in rows if r["species"] == sp and r["dose_cm2"] == dose]
            subset.sort(key=lambda r: r["anneal_stage"])
            stage = [r["anneal_stage"] for r in subset]
            r_s = [r["sheet_resistance_ohm_sq"] for r in subset]
            mu = [r["mobility_cm2_Vs"] for r in subset]
            ls = linestyles[di % len(linestyles)]
            label = f"{sp} ({dose:.0e} cm⁻²)"
            ax_r.plot(stage, r_s, color=colors[si], linestyle=ls, marker="o", markersize=3, label=label)
            ax_mu.plot(stage, mu, color=colors[si], linestyle=ls, marker="o", markersize=3, label=label)

    ax_r.set_yscale("log")
    ax_r.set_xlabel("Anneal stage")
    ax_r.set_ylabel("Sheet resistance [Ω/sq]")
    ax_r.set_title("Sheet Resistance Recovery")
    ax_r.grid(alpha=0.3)

    ax_mu.set_yscale("log")
    ax_mu.set_xlabel("Anneal stage")
    ax_mu.set_ylabel("Carrier mobility [cm²/(V·s)]")
    ax_mu.set_title("Carrier Mobility vs. Anneal Stage")
    ax_mu.grid(alpha=0.3)

    handles, labels = ax_r.get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=min(4, len(labels)), bbox_to_anchor=(0.5, -0.08))
    fig.suptitle("ODIQ-ZnSe: 4-Point Probe Recovery Simulation (synthetic)", fontsize=13)
    fig.tight_layout()

    if save_path:
        fig.savefig(save_path, dpi=150, bbox_inches="tight")
        print(f"Saved plot to {save_path}")
    else:
        plt.show()


def parse_args():
    parser = argparse.ArgumentParser(description="Simulate 4-point probe sheet resistance / mobility recovery for ion-implanted ZnSe.")
    parser.add_argument("--species", nargs="+", default=list(DEFAULT_SPECIES.keys()), choices=list(DEFAULT_SPECIES.keys()), help="Implant species to simulate.")
    parser.add_argument("--doses", nargs="+", type=float, default=[1e13, 1e14, 1e15], help="Implant doses in ions/cm^2.")
    parser.add_argument("--stages", type=int, default=8, help="Number of anneal stages to simulate.")
    parser.add_argument("--save-csv", type=str, default=None, help="Path to save results as CSV.")
    parser.add_argument("--save-plot", type=str, default=None, help="Path to save plot as PNG (otherwise displays interactively).")
    # In a Colab environment, the kernel passes its own arguments (e.g., -f).
    # We use parse_known_args() to ignore these and only parse the arguments
    # defined in the script.
    args, unknown = parser.parse_known_args()
    return args


def main():
    args = parse_args()
    rows = run_simulation(args.species, args.doses, n_stages=args.stages)

    if args.save_csv:
        save_csv(rows, args.save_csv)

    plot_results(rows, save_path=args.save_plot)


if __name__ == "__main__":
    main()

main()